spring:
  thymeleaf:
    cache: false
  datasource:
    #??????????????
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondkill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #???????????
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.137.101
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait:  10000ms
        max-idle: 200
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*mapper.xml
  type-aliases-package: com.example.secondkill.pojo
logging:
  level:
    com.example.secondkill.mapper: debug

